
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false   # disable security
      - xpack.security.http.ssl.enabled=false
      - ELASTIC_PASSWORD=${ES_PASSWORD}
    ports:
      - "9200:9200"
    networks:
      - elk-network

  logstash:
    image: docker.elastic.co/logstash/logstash:9.0.4
    environment:
      - ELASTICSEARCH_HOST=http://es:9200
      - ELASTIC_PASSWORD=${ES_PASSWORD}
    ports:
      - "5044:5044"
    networks:
      - elk-network
    depends_on:
      - es
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline/


  kibana:
    image: docker.elastic.co/kibana/kibana:9.0.4
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
      # - ELASTICSEARCH_USERNAME=${ES_USER}
      # - ELASTICSEARCH_PASSWORD=${ES_PASSWORD}
    ports:
      - "5601:5601"
    networks:
      - elk-network
    depends_on:
      - es

networks:
  elk-network:
    driver: bridge

